services:
  academie-prod:
    image: academie:prod
    container_name: academie-prod
    restart: unless-stopped
    environment:
      GITHUB_CLIENT_ID: ${PROD_GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${PROD_GITHUB_CLIENT_SECRET}
      SITE_URL: https://academie.sintlukas.com
    networks:
      - pangolin
    labels:
      - traefik.enable=true
      - traefik.http.routers.academie-prod.rule=Host(`academie.sintlukas.com`)
      - traefik.http.routers.academie-prod.entrypoints=websecure
      - traefik.http.routers.academie-prod.tls=true
      - traefik.http.routers.academie-prod.tls.certresolver=letsencrypt
      - traefik.http.services.academie-prod.loadbalancer.server.port=3000
      - traefik.docker.network=pangolin

  academie-staging:
    image: academie:staging
    container_name: academie-staging
    restart: unless-stopped
    environment:
      GITHUB_CLIENT_ID: ${STAGING_GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${STAGING_GITHUB_CLIENT_SECRET}
      SITE_URL: https://academie-staging.sintlukas.com
    networks:
      - pangolin
    labels:
      - traefik.enable=true
      - traefik.http.routers.academie-staging.rule=Host(`academie-staging.sintlukas.com`)
      - traefik.http.routers.academie-staging.entrypoints=websecure
      - traefik.http.routers.academie-staging.tls=true
      - traefik.http.routers.academie-staging.tls.certresolver=letsencrypt
      - traefik.http.services.academie-staging.loadbalancer.server.port=3000
      - traefik.docker.network=pangolin

networks:
  pangolin:
    external: true
    name: pangolin
