FROM node:22-alpine AS build

WORKDIR /app

RUN npm install -g pnpm

COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile

COPY . .
ARG MAPBOX_ACCESS_TOKEN
ENV MAPBOX_ACCESS_TOKEN=$MAPBOX_ACCESS_TOKEN
RUN pnpm build

FROM node:22-alpine AS runtime

WORKDIR /app

COPY --from=build /app/.output /app/.output

ENV NODE_ENV=production
ENV HOST=0.0.0.0
ENV PORT=3000

EXPOSE 3000

CMD ["node", ".output/server/index.mjs"]
